### ISSUE TITLE
Build breaks when installing libdivvun - wrong hfst dep

### ISSUE THREAD

**Issue by snomos** [giellalt/giella-core#14]
```sh
/bin/bash -c wget -q https://apertium.projectjj.com/apt/install-nightly.sh -O install-nightly.sh && bash install-nightly.sh
[1156](https://github.com/giellalt/lang-sma/runs/5120834717?check_suite_focus=true#step:6:1156)

[1157](https://github.com/giellalt/lang-sma/runs/5120834717?check_suite_focus=true#step:6:1157)
Cleaning up old install, if any...
[1158](https://github.com/giellalt/lang-sma/runs/5120834717?check_suite_focus=true#step:6:1158)
Determining Debian/Ubuntu codename...
[1159](https://github.com/giellalt/lang-sma/runs/5120834717?check_suite_focus=true#step:6:1159)
install-nightly.sh: line 25: lsb_release: command not found
[1160](https://github.com/giellalt/lang-sma/runs/5120834717?check_suite_focus=true#step:6:1160)
Found evidence of bionic...
[1161](https://github.com/giellalt/lang-sma/runs/5120834717?check_suite_focus=true#step:6:1161)
Settling for bionic - enabling the Apertium nightly repo...
[1162](https://github.com/giellalt/lang-sma/runs/5120834717?check_suite_focus=true#step:6:1162)
Installing Apertium GnuPG key to /etc/apt/trusted.gpg.d/apertium.gpg
[1163](https://github.com/giellalt/lang-sma/runs/5120834717?check_suite_focus=true#step:6:1163)
2022-02-09 06:07:26 URL:https://apertium.projectjj.com/apt/apertium-packaging.public.gpg [3725/3725] -> "-" [1]
[1164](https://github.com/giellalt/lang-sma/runs/5120834717?check_suite_focus=true#step:6:1164)
Installing package override to /etc/apt/preferences.d/apertium.pref
[1165](https://github.com/giellalt/lang-sma/runs/5120834717?check_suite_focus=true#step:6:1165)
2022-02-09 06:07:27 URL:https://apertium.projectjj.com/apt/apertium.pref [65/65] -> "-" [1]
[1166](https://github.com/giellalt/lang-sma/runs/5120834717?check_suite_focus=true#step:6:1166)
Creating /etc/apt/sources.list.d/apertium.list
[1167](https://github.com/giellalt/lang-sma/runs/5120834717?check_suite_focus=true#step:6:1167)
Running apt-get update...
[1168](https://github.com/giellalt/lang-sma/runs/5120834717?check_suite_focus=true#step:6:1168)
All done - enjoy the packages! If you just want all core tools, do: sudo apt-get install apertium-all-dev
[1169](https://github.com/giellalt/lang-sma/runs/5120834717?check_suite_focus=true#step:6:1169)
/usr/bin/apt-get install -qfy foma hfst libhfst-dev cg3-dev divvun-gramcheck
[1170](https://github.com/giellalt/lang-sma/runs/5120834717?check_suite_focus=true#step:6:1170)
Reading package lists...
[1171](https://github.com/giellalt/lang-sma/runs/5120834717?check_suite_focus=true#step:6:1171)
Building dependency tree...
[1172](https://github.com/giellalt/lang-sma/runs/5120834717?check_suite_focus=true#step:6:1172)
Reading state information...
[1173](https://github.com/giellalt/lang-sma/runs/5120834717?check_suite_focus=true#step:6:1173)
Some packages could not be installed. This may mean that you have
[1174](https://github.com/giellalt/lang-sma/runs/5120834717?check_suite_focus=true#step:6:1174)
requested an impossible situation or if you are using the unstable
[1175](https://github.com/giellalt/lang-sma/runs/5120834717?check_suite_focus=true#step:6:1175)
distribution that some required packages have not yet been created
[1176](https://github.com/giellalt/lang-sma/runs/5120834717?check_suite_focus=true#step:6:1176)
or been moved out of Incoming.
[1177](https://github.com/giellalt/lang-sma/runs/5120834717?check_suite_focus=true#step:6:1177)
The following information may help to resolve the situation:
[1178](https://github.com/giellalt/lang-sma/runs/5120834717?check_suite_focus=true#step:6:1178)

[1179](https://github.com/giellalt/lang-sma/runs/5120834717?check_suite_focus=true#step:6:1179)
The following packages have unmet dependencies:
[1180](https://github.com/giellalt/lang-sma/runs/5120834717?check_suite_focus=true#step:6:1180)
 hfst : Depends: libhfst55 (= 3.16.0+g3859~3a99b739-1~bionic1) but it is not going to be installed
[1181](https://github.com/giellalt/lang-sma/runs/5120834717?check_suite_focus=true#step:6:1181)
 libhfst-dev : Depends: libhfst55 (= 3.16.0+g3859~3a99b739-1~bionic1) but it is not going to be installed
[1182](https://github.com/giellalt/lang-sma/runs/5120834717?check_suite_focus=true#step:6:1182)
E: Unable to correct problems, you have held broken packages.
[1183](https://github.com/giellalt/lang-sma/runs/5120834717?check_suite_focus=true#step:6:1183)
Error: The process '/usr/bin/apt-get' failed with exit code 100
[1184](https://github.com/giellalt/lang-sma/runs/5120834717?check_suite_focus=true#step:6:1184)
    at ExecState._setResult (/__w/_actions/divvun/actions/master/node_modules/@actions/exec/lib/toolrunner.js:574:25)
[1185](https://github.com/giellalt/lang-sma/runs/5120834717?check_suite_focus=true#step:6:1185)
    at ExecState.CheckComplete (/__w/_actions/divvun/actions/master/node_modules/@actions/exec/lib/toolrunner.js:557:18)
[1186](https://github.com/giellalt/lang-sma/runs/5120834717?check_suite_focus=true#step:6:1186)
    at ChildProcess.<anonymous> (/__w/_actions/divvun/actions/master/node_modules/@actions/exec/lib/toolrunner.js:451:27)
[1187](https://github.com/giellalt/lang-sma/runs/5120834717?check_suite_focus=true#step:6:1187)
    at ChildProcess.emit (events.js:210:5)
[1188](https://github.com/giellalt/lang-sma/runs/5120834717?check_suite_focus=true#step:6:1188)
    at maybeClose (internal/child_process.js:1021:16)
[1189](https://github.com/giellalt/lang-sma/runs/5120834717?check_suite_focus=true#step:6:1189)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
[1190](https://github.com/giellalt/lang-sma/runs/5120834717?check_suite_focus=true#step:6:1190)
##[debug]Node Action run completed with exit code 1
[1191](https://github.com/giellalt/lang-sma/runs/5120834717?check_suite_focus=true#step:6:1191)
```

Cf https://github.com/giellalt/lang-sma/runs/5120834717?check_suite_focus=true

@TinoDidriksen or @unhammer - is this related to the Python issue in libdivvun? In any case, this is high priority - it blocks every single build using GitHub Actions.

**Comment by TinoDidriksen** [comment]
Fixed
