### ISSUE TITLE
adj-ak.yaml test failing (Bugzilla Bug 1453)

### ISSUE THREAD

**Issue by albbas** [giellalt/giella-core#269]
This issue was created automatically with bugzilla2github
# Bugzilla Bug 1453
Date: 2012-10-03T12:56:26+02:00
From: @ilm024 (Originally created by @ilm024)
To:   @snomos

Last updated: 2012-10-03T17:59:26+02:00

**Comment by albbas** [comment]
## Comment 7009
Date: 2012-10-03 12:56:26 +0200
From: @ilm024

When i "make check" in SMJ one of the yaml tests is failing (adj-ak.yaml). 
I can't understand why.


Subtest 4 - xerox: Testing ./adj-ak.yaml using ./../../../src/analyser.gt.xfst

Traceback (most recent call last):
  File "/Users/Inga/langtech/main/gtcore/scripts/morph-test.py", line 578, in <module>
    main()
  File "/Users/Inga/langtech/main/gtcore/scripts/morph-test.py", line 573, in main
    ui.start()
  File "/Users/Inga/langtech/main/gtcore/scripts/morph-test.py", line 566, in start
    ret = self.run()
  File "/Users/Inga/langtech/main/gtcore/scripts/morph-test.py", line 266, in run
    self.run_tests(self.args['test'])
  File "/Users/Inga/langtech/main/gtcore/scripts/morph-test.py", line 327, in run_tests
    if self.args.get('surface'): self.run_test(t, False)
  File "/Users/Inga/langtech/main/gtcore/scripts/morph-test.py", line 394, in run_test
    actual_results = set(self.results[f][test])
KeyError: 'skárbbis'

Test failed. To rerun with more details, please do:

pushd /Users/Inga/langtech/main/langs/smj/test/src/morphology; /opt/local/bin/python3.2 /Users/Inga/langtech/main/gtcore/scripts/morph-test.py -c -i -S xerox --app /Users/Inga/bin/lookup --gen ./../../../src/generator.gt.xfst --morph ./../../../src/analyser.gt.xfst ./adj-ak.yaml; popd

**Comment by albbas** [comment]
## Comment 7010
Date: 2012-10-03 17:59:26 +0200
From: @snomos

Fixed in r63555. The error was caused by double entries of lines like

    skárbak+A+Attr: skárbbis

because skárbak was given as lemma also in the stuorak test. The same lemma + tag set can only be defined once.
