### ISSUE TITLE
`lexc-giella-style.py` fails in several ways

### ISSUE THREAD

**Issue by snomos** [giellalt/giella-core#30]
```python
./giella-core/devtools/lexc-giella-style.py -h                                   
Traceback (most recent call last):
  File "/Users/smo036/langtech/gut/giellalt/./giella-core/devtools/lexc-giella-style.py", line 1015, in <module>
    ARGS = parse_options()
           ^^^^^^^^^^^^^^^
  File "/Users/smo036/langtech/gut/giellalt/./giella-core/devtools/lexc-giella-style.py", line 1003, in parse_options
    arguments = parser.parse_args()
                ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/argparse.py", line 1869, in parse_args
    args, argv = self.parse_known_args(args, namespace)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/argparse.py", line 1902, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/argparse.py", line 2114, in _parse_known_args
    start_index = consume_optional(start_index)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/argparse.py", line 2054, in consume_optional
    take_action(action, args, option_string)
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/argparse.py", line 1978, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/argparse.py", line 1119, in __call__
    parser.print_help()
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/argparse.py", line 2601, in print_help
    self._print_message(self.format_help(), file)
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/argparse.py", line 2607, in _print_message
    file.write(message)
  File "<frozen codecs>", line 378, in write
TypeError: write() argument must be str, not bytes
```

And:

```python
./giella-core/devtools/lexc-giella-style.py --align lang-sma/src/fst/root.lexc   
Traceback (most recent call last):
  File "/Users/smo036/langtech/gut/giellalt/./giella-core/devtools/lexc-giella-style.py", line 1031, in <module>
    NEWLINES.extend(align_lexicon(READLINES))
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smo036/langtech/gut/giellalt/./giella-core/devtools/lexc-giella-style.py", line 962, in align_lexicon
    lines.parse_lines(lexc_lines)
  File "/Users/smo036/langtech/gut/giellalt/./giella-core/devtools/lexc-giella-style.py", line 740, in parse_lines
    line_dict = parse_line(content)
                ^^^^^^^^^^^^^^^^^^^
  File "/Users/smo036/langtech/gut/giellalt/./giella-core/devtools/lexc-giella-style.py", line 917, in parse_line
    line_dict = defaultdict(unicode)
                            ^^^^^^^
NameError: name 'unicode' is not defined
```

**Comment by albbas** [comment]
Fixed in #[ed54f1eb8f8](https://github.com/giellalt/giella-core/commit/ed54f1eb8f80cc1dc9d66fe4401aabb2f1714aa3)
